[package]
name = "drawback_chess"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12"
shakmaty = "0.26.0"
rand = "0.8.5"
futures-lite = "1.13"
arrayvec = "0.7.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0" 